name: Deploy

on:
  push:
    branches: [ master, setup_workflows ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Collect packages
      run: |
        mkdir aftifacts
        cp Config.Numerge.json aftifacts/
        mkdir -p aftifacts/input/
        cp *.nupkg aftifacts/input/
    - name: Upload aftifacts
      uses: actions/upload-artifact@v2
      with:
        name: aftifacts
        path: aftifacts/
  numerge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Numerge
        uses: actions/checkout@v2.3.4
        with:
          repository: CreateLab/Numerge
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - name: Build Numerge
        run: dotnet build
      - name: Download packages
        uses: actions/download-artifact@v2.0.8
        with:
          name: aftifacts
          path: aftifacts
      - name: Merge packages
        run: |
          mkdir aftifacts/output/
          dotnet run --project Numerge.Console aftifacts/Config.Numerge.json aftifacts/input/ aftifacts/output/
      - name: Publish to Nuget
        run: dotnet nuget push "aftifacts/output/*.nupkg" --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
      - name: Publish to Nuget
        run: dotnet nuget push "aftifacts/output/*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/AvaloniaUtils/index.json